spring:
  application:
    name: resources-service

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: resources

server:
  port: 8082

SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/resources

management:
  endpoints:
    web:
      exposure:
        include: *