server:
  port: 8083

spring:
  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8181/realms/enter-balance-test-realm

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  endpoints:
    web:
      exposure:
        include: *