server:
  port: 8084

spring:
  application:
    name: company-service
  security:
    oauth2:
      resourceserve:
        jwt:
          issuer-uri: http://keycloak:8181/realms/enter-balance-test-realm
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none

test:
  str:
    text: test-str-config-dev
